### PR TITLE
use full local binary path for cross-env

### PR DESCRIPTION
**Pull request by superhawk610**
Including the local binary path for cross-env allows scripts to run without having cross-env installed globally.

### CODE REVIEW

**Comment by bennygenel** [comment]
@superhawk610  Thank you for the PR. Is this a problem on linux bases systems? On Windows I can run the command as is without having it globally installed.

**Comment by superhawk610** [comment]
What shell on Windows are you using, cmd? I'm running Git Bash on Windows, it allows Unix-like syntax. I think it's a fairly popular shell.

**Comment by bennygenel** [comment]
@superhawk610 I just tried it on CMD, PowerShell and GitBash on Windows 10 machine and there were no problems with running. It would be nice to confirm this problem on other machines before merging.

**Comment by superhawk610** [comment]
Hmm. Do you have your local node_modules from guppy included in your PATH
variable? If not, I'm not sure how your system would know where to look for
`cross-env`. Are you sure you don't have it installed globally?

**Comment by bennygenel** [comment]
@superhawk610 I have not set any PATH vars. `npm bin` command returns the local `node_modules` folder as expected. As far as I know when you run a command npm first looks for a local bin folder if it contains the command then it checks for the global bin folder.

**Comment by superhawk610** [comment]
Just tested it from another Windows PC and it worked fine, just like you said. Time to figure out what's wrong with my main NPM install, I guess. I didn't know npm scripts looked in that `npm bin` directory in addition to the PATH, thanks for your help.

**Pull request closed without merging**
